# Generated by Django 4.2 on 2024-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Собирается', 'Собирается'), ('on_the_way', 'В пути'), ('delivered', 'Доставлено'), ('received', 'Получено')], default='going_to', max_length=255, verbose_name='Статус доставки'),
        ),
    ]
