# Generated by Django 4.2 on 2024-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Собирается', 'Собирается'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено'), ('Получено', 'Получено')], default='going_to', max_length=255, verbose_name='Статус доставки'),
        ),
    ]
