# Generated by Django 4.2 on 2024-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='image',
            field=models.ImageField(default=True, upload_to='products_photo/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
