# Generated by Django 4.2 on 2024-08-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productinorder_delete_productincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.productinorder', verbose_name='Продукт'),
        ),
    ]
