# Generated by Django 4.2 on 2024-08-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
