# Generated by Django 4.2 on 2024-08-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productimage', verbose_name='Изображение'),
        ),
    ]
