# Generated by Django 4.2 on 2024-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_wishlist_image_wishlist_product_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка в процентах'),
        ),
    ]
