# Generated by Django 4.2 on 2024-08-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_not_discount',
        ),
    ]
