# Generated by Django 4.2 on 2024-08-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_categories_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
