# Generated by Django 4.2 on 2024-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_order_options_alter_productinorder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='product',
        ),
        migrations.AddField(
            model_name='categories',
            name='product',
            field=models.ManyToManyField(related_name='Categories', to='products.product', verbose_name='Продукт'),
        ),
    ]
