# Generated by Django 4.2 on 2024-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_categories_product_categories_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='characteristic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единицы измерения'),
        ),
    ]
