# Generated by Django 4.2 on 2024-08-26 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_product_options_characteristic_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='description',
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='amount',
            field=models.PositiveSmallIntegerField(default=True, validators=[django.core.validators.MinValueValidator(1, 'Количество не может быть меньше 1')], verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='measurement_unit',
            field=models.CharField(max_length=100, verbose_name='Единицы измерения'),
        ),
    ]
