# Generated by Django 4.2 on 2024-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_characteristic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единицы измерения'),
        ),
    ]
