# Generated by Django 4.2 on 2024-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_characteristic_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Собирается', 'Собирается'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено'), ('Получено', 'Получено')], default='Создан', max_length=255, verbose_name='Статус доставки'),
        ),
    ]
