# Generated by Django 4.2 on 2024-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Параметры товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='param',
            field=models.CharField(default=True, max_length=500, verbose_name='Параметр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Сумма к оплате'),
        ),
        migrations.AddField(
            model_name='product',
            name='param_value',
            field=models.ManyToManyField(related_name='param_value', to='products.paramproduct'),
        ),
    ]
