# Generated by Django 4.2 on 2024-08-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_paramproduct_product_param_alter_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название параметра')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение параметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.parameter')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='param',
        ),
        migrations.RemoveField(
            model_name='product',
            name='param_value',
        ),
        migrations.DeleteModel(
            name='ParamProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.parametervalue'),
        ),
    ]
