# Generated by Django 4.2 on 2024-08-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_parameter_parametervalue_remove_product_param_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'verbose_name': 'Значение параметра', 'verbose_name_plural': 'Значения параметра'},
        ),
    ]
