# Generated by Django 4.2 on 2024-08-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_parameter_options_alter_parametervalue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.parameter', verbose_name='Параметр'),
        ),
    ]
