# Generated by Django 4.2 on 2024-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_parametervalue_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.CharField(blank=True, max_length=100, verbose_name='Параметр'),
        ),
    ]
