# Generated by Django 4.2 on 2024-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_product_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='parameters',
            field=models.CharField(blank=True, max_length=100, verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='cart',
            name='parameters_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Значение параметра'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
