# Generated by Django 4.2 on 2024-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_cart_parameters_cart_parameters_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единицы измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единицы измерения'),
        ),
    ]
