# Generated by Django 4.2 on 2024-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
    ]
