# Generated by Django 4.2 on 2024-08-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_cart_color_productinorder_color_wishlist_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='color',
        ),
    ]
