# Generated by Django 4.2 on 2024-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_remove_cart_color_remove_productinorder_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единицы измерения'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='parameters',
            field=models.CharField(blank=True, max_length=100, verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='parameters_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Значение параметра'),
        ),
    ]
