# Generated by Django 4.2 on 2026-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_order_date_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Собирается', 'Собирается'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено'), ('Получено', 'Получено'), ('Отменен', 'Отменен')], default='Создан', max_length=255, verbose_name='Статус доставки'),
        ),
    ]
