# Generated by Django 4.2 on 2026-07-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0050_order_status_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Товар'), ('category', 'Категория'), ('query', 'Поиск')], max_length=20, verbose_name='Тип')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Интерес пользователя',
                'verbose_name_plural': 'Интересы пользователей',
            },
        ),
        migrations.CreateModel(
            name='ProductPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('search_hits', models.PositiveIntegerField(default=0, verbose_name='Попадания в поиск')),
                ('wishlist_adds', models.PositiveIntegerField(default=0, verbose_name='В избранное')),
                ('cart_adds', models.PositiveIntegerField(default=0, verbose_name='В корзину')),
                ('purchases', models.PositiveIntegerField(default=0, verbose_name='Покупки')),
                ('score', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Рейтинг')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Популярность товара',
                'verbose_name_plural': 'Популярность товаров',
                'ordering': ['-score'],
            },
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', 'kind', '-weight'], name='products_us_user_id_6ea390_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'key'), name='uniq_user_interest_kind_key'),
        ),
    ]
